### ISSUE TITLE
Cannot compile on openSUSE Leap 15.6

### ISSUE THREAD

**Issue by Chirunos** [lichray/nvi2#138]
nvi2 2.2.1
Ninja 1.10 (Main Repository)
CMake 3.28.3 (Main Repository)
GCC 14.2 (Update repository with updates from SUSE Linux Enterprise 15)
`libdb-4_8-devel` 4.8.30 (Main Repository)
`libbsd-devel` 0.11.7 ([home_ahmedmoselhi2](https://build.opensuse.org/package/show/home%3Aahmedmoselhi2/libbsd))

Terminal output:
```
$ ninja -C build
ninja: Entering directory `build'
[8/118] Building C object CMakeFiles/nvi.dir/Debug/cl/cl_main.c.o
FAILED: CMakeFiles/nvi.dir/Debug/cl/cl_main.c.o 
/usr/bin/cc -DCOMLOG -DDEBUG -DLIBBSD_OVERLAY -D_XOPEN_SOURCE_EXTENDED -D__REGEX_PRIVATE -DCMAKE_INTDIR=\"Debug\" -I/home/user/editor/nvi2/build -I/home/user/editor/nvi2/regex -g   -isystem /usr/include/bsd -Wall -Wno-parentheses -Wno-uninitialized -Wmissing-prototypes -Wsystem-headers -Wno-string-compare -Wstack-protector -fstack-protector -Wstrict-aliasing -fstrict-aliasing -MD -MT CMakeFiles/nvi.dir/Debug/cl/cl_main.c.o -MF CMakeFiles/nvi.dir/Debug/cl/cl_main.c.o.d -o CMakeFiles/nvi.dir/Debug/cl/cl_main.c.o -c /home/user/editor/nvi2/cl/cl_main.c
In file included from /home/user/editor/nvi2/cl/../common/common.h:82,
                 from /home/user/editor/nvi2/cl/cl_main.c:29:
/home/user/editor/nvi2/cl/../common/cut.h:33:9: error: unknown type name ‘recno_t’
   33 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:85:
/home/user/editor/nvi2/cl/../common/mark.h:24:9: error: unknown type name ‘recno_t’
   24 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/mark.h:30:9: error: unknown type name ‘recno_t’
   30 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:87:
/home/user/editor/nvi2/cl/../common/../ex/ex.h:69:9: error: unknown type name ‘recno_t’
   69 |         recno_t start, stop;            /* Start/stop of the range. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:77:9: error: unknown type name ‘recno_t’
   77 |         recno_t   if_lno;               /* Associated line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:94:9: error: unknown type name ‘recno_t’
   94 |         recno_t   range_lno;            /* @/global range: set line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:113:9: error: unknown type name ‘recno_t’
  113 |         recno_t   lineno;               /* Command: line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/../ex/ex.h:231:
/home/user/editor/nvi2/cl/../common/../ex/extern.h:44:32: error: unknown type name ‘recno_t’
   44 | int ex_g_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:72:46: error: unknown type name ‘recno_t’
   72 | int ex_readfp(SCR *, char *, FILE *, MARK *, recno_t *, int);
      |                                              ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:78:22: error: unknown type name ‘recno_t’
   78 | int sscr_exec(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:41: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:50: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                                  ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:88:
/home/user/editor/nvi2/cl/../common/gs.h:26:9: error: unknown type name ‘recno_t’
   26 |         recno_t  lno;                   /* 1-N: file cursor line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/gs.h:90:9: error: unknown type name ‘recno_t’
   90 |         recno_t   if_lno;               /* Current associated line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:89:
/home/user/editor/nvi2/cl/../common/screen.h:60:9: error: unknown type name ‘recno_t’
   60 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:72:9: error: unknown type name ‘recno_t’
   72 |         recno_t  rptlchange;            /* Ex/vi: last L_CHANGED lno. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:73:9: error: unknown type name ‘recno_t’
   73 |         recno_t  rptlines[L_YANKED + 1];/* Ex/vi: lines changed by last op. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:79:9: error: unknown type name ‘recno_t’
   79 |         recno_t  defscroll;             /* Vi: ^D, ^U scroll information. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:90:
/home/user/editor/nvi2/cl/../common/exf.h:22:9: error: unknown type name ‘recno_t’
   22 |         recno_t  c_lno;                 /* Cached line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:23:9: error: unknown type name ‘recno_t’
   23 |         recno_t  c_nlines;              /* Cached lines in the file. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:28:9: error: unknown type name ‘recno_t’
   28 |         recno_t  l_high;                /* Log last + 1 record number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:29:9: error: unknown type name ‘recno_t’
   29 |         recno_t  l_cur;                 /* Log current record number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:94:
/home/user/editor/nvi2/cl/../common/extern.h:6:21: error: unknown type name ‘recno_t’
    6 | int cut_line(SCR *, recno_t, size_t, size_t, CB *);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:35:20: error: unknown type name ‘recno_t’
   35 | int db_eget(SCR *, recno_t, CHAR_T **, size_t *, int *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:36:19: error: unknown type name ‘recno_t’
   36 | int db_get(SCR *, recno_t, u_int32_t, CHAR_T **, size_t *);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:37:22: error: unknown type name ‘recno_t’
   37 | int db_delete(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:38:27: error: unknown type name ‘recno_t’
   38 | int db_append(SCR *, int, recno_t, CHAR_T *, size_t);
      |                           ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:39:22: error: unknown type name ‘recno_t’
   39 | int db_insert(SCR *, recno_t, CHAR_T *, size_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:40:19: error: unknown type name ‘recno_t’
   40 | int db_set(SCR *, recno_t, CHAR_T *, size_t);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:41:21: error: unknown type name ‘recno_t’
   41 | int db_exist(SCR *, recno_t);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:42:20: error: unknown type name ‘recno_t’
   42 | int db_last(SCR *, recno_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:43:20: error: unknown type name ‘recno_t’
   43 | int db_rget(SCR *, recno_t, char **, size_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:44:20: error: unknown type name ‘recno_t’
   44 | int db_rset(SCR *, recno_t, char *, size_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:45:20: error: unknown type name ‘recno_t’
   45 | void db_err(SCR *, recno_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:49:21: error: unknown type name ‘recno_t’
   49 | int log_line(SCR *, recno_t, u_int);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:60:32: error: unknown type name ‘recno_t’
   60 | int mark_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:65:25: error: unknown type name ‘recno_t’
   65 | void msgq_status(SCR *, recno_t, u_int);
      |                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:121:21: error: unknown type name ‘recno_t’
  121 | int nonblank(SCR *, recno_t, size_t *);
      |                     ^~~~~~~
[9/118] Building C object CMakeFiles/nvi.dir/Debug/cl/cl_read.c.o
FAILED: CMakeFiles/nvi.dir/Debug/cl/cl_read.c.o 
/usr/bin/cc -DCOMLOG -DDEBUG -DLIBBSD_OVERLAY -D_XOPEN_SOURCE_EXTENDED -D__REGEX_PRIVATE -DCMAKE_INTDIR=\"Debug\" -I/home/user/editor/nvi2/build -I/home/user/editor/nvi2/regex -g   -isystem /usr/include/bsd -Wall -Wno-parentheses -Wno-uninitialized -Wmissing-prototypes -Wsystem-headers -Wno-string-compare -Wstack-protector -fstack-protector -Wstrict-aliasing -fstrict-aliasing -MD -MT CMakeFiles/nvi.dir/Debug/cl/cl_read.c.o -MF CMakeFiles/nvi.dir/Debug/cl/cl_read.c.o.d -o CMakeFiles/nvi.dir/Debug/cl/cl_read.c.o -c /home/user/editor/nvi2/cl/cl_read.c
In file included from /home/user/editor/nvi2/cl/../common/common.h:82,
                 from /home/user/editor/nvi2/cl/cl_read.c:27:
/home/user/editor/nvi2/cl/../common/cut.h:33:9: error: unknown type name ‘recno_t’
   33 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:85:
/home/user/editor/nvi2/cl/../common/mark.h:24:9: error: unknown type name ‘recno_t’
   24 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/mark.h:30:9: error: unknown type name ‘recno_t’
   30 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:87:
/home/user/editor/nvi2/cl/../common/../ex/ex.h:69:9: error: unknown type name ‘recno_t’
   69 |         recno_t start, stop;            /* Start/stop of the range. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:77:9: error: unknown type name ‘recno_t’
   77 |         recno_t   if_lno;               /* Associated line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:94:9: error: unknown type name ‘recno_t’
   94 |         recno_t   range_lno;            /* @/global range: set line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:113:9: error: unknown type name ‘recno_t’
  113 |         recno_t   lineno;               /* Command: line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/../ex/ex.h:231:
/home/user/editor/nvi2/cl/../common/../ex/extern.h:44:32: error: unknown type name ‘recno_t’
   44 | int ex_g_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:72:46: error: unknown type name ‘recno_t’
   72 | int ex_readfp(SCR *, char *, FILE *, MARK *, recno_t *, int);
      |                                              ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:78:22: error: unknown type name ‘recno_t’
   78 | int sscr_exec(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:41: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:50: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                                  ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:88:
/home/user/editor/nvi2/cl/../common/gs.h:26:9: error: unknown type name ‘recno_t’
   26 |         recno_t  lno;                   /* 1-N: file cursor line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/gs.h:90:9: error: unknown type name ‘recno_t’
   90 |         recno_t   if_lno;               /* Current associated line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:89:
/home/user/editor/nvi2/cl/../common/screen.h:60:9: error: unknown type name ‘recno_t’
   60 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:72:9: error: unknown type name ‘recno_t’
   72 |         recno_t  rptlchange;            /* Ex/vi: last L_CHANGED lno. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:73:9: error: unknown type name ‘recno_t’
   73 |         recno_t  rptlines[L_YANKED + 1];/* Ex/vi: lines changed by last op. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:79:9: error: unknown type name ‘recno_t’
   79 |         recno_t  defscroll;             /* Vi: ^D, ^U scroll information. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:90:
/home/user/editor/nvi2/cl/../common/exf.h:22:9: error: unknown type name ‘recno_t’
   22 |         recno_t  c_lno;                 /* Cached line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:23:9: error: unknown type name ‘recno_t’
   23 |         recno_t  c_nlines;              /* Cached lines in the file. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:28:9: error: unknown type name ‘recno_t’
   28 |         recno_t  l_high;                /* Log last + 1 record number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:29:9: error: unknown type name ‘recno_t’
   29 |         recno_t  l_cur;                 /* Log current record number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:94:
/home/user/editor/nvi2/cl/../common/extern.h:6:21: error: unknown type name ‘recno_t’
    6 | int cut_line(SCR *, recno_t, size_t, size_t, CB *);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:35:20: error: unknown type name ‘recno_t’
   35 | int db_eget(SCR *, recno_t, CHAR_T **, size_t *, int *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:36:19: error: unknown type name ‘recno_t’
   36 | int db_get(SCR *, recno_t, u_int32_t, CHAR_T **, size_t *);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:37:22: error: unknown type name ‘recno_t’
   37 | int db_delete(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:38:27: error: unknown type name ‘recno_t’
   38 | int db_append(SCR *, int, recno_t, CHAR_T *, size_t);
      |                           ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:39:22: error: unknown type name ‘recno_t’
   39 | int db_insert(SCR *, recno_t, CHAR_T *, size_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:40:19: error: unknown type name ‘recno_t’
   40 | int db_set(SCR *, recno_t, CHAR_T *, size_t);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:41:21: error: unknown type name ‘recno_t’
   41 | int db_exist(SCR *, recno_t);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:42:20: error: unknown type name ‘recno_t’
   42 | int db_last(SCR *, recno_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:43:20: error: unknown type name ‘recno_t’
   43 | int db_rget(SCR *, recno_t, char **, size_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:44:20: error: unknown type name ‘recno_t’
   44 | int db_rset(SCR *, recno_t, char *, size_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:45:20: error: unknown type name ‘recno_t’
   45 | void db_err(SCR *, recno_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:49:21: error: unknown type name ‘recno_t’
   49 | int log_line(SCR *, recno_t, u_int);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:60:32: error: unknown type name ‘recno_t’
   60 | int mark_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:65:25: error: unknown type name ‘recno_t’
   65 | void msgq_status(SCR *, recno_t, u_int);
      |                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:121:21: error: unknown type name ‘recno_t’
  121 | int nonblank(SCR *, recno_t, size_t *);
      |                     ^~~~~~~
[10/118] Building C object CMakeFiles/nvi.dir/Debug/cl/cl_funcs.c.o
FAILED: CMakeFiles/nvi.dir/Debug/cl/cl_funcs.c.o 
/usr/bin/cc -DCOMLOG -DDEBUG -DLIBBSD_OVERLAY -D_XOPEN_SOURCE_EXTENDED -D__REGEX_PRIVATE -DCMAKE_INTDIR=\"Debug\" -I/home/user/editor/nvi2/build -I/home/user/editor/nvi2/regex -g   -isystem /usr/include/bsd -Wall -Wno-parentheses -Wno-uninitialized -Wmissing-prototypes -Wsystem-headers -Wno-string-compare -Wstack-protector -fstack-protector -Wstrict-aliasing -fstrict-aliasing -MD -MT CMakeFiles/nvi.dir/Debug/cl/cl_funcs.c.o -MF CMakeFiles/nvi.dir/Debug/cl/cl_funcs.c.o.d -o CMakeFiles/nvi.dir/Debug/cl/cl_funcs.c.o -c /home/user/editor/nvi2/cl/cl_funcs.c
In file included from /home/user/editor/nvi2/cl/../common/common.h:82,
                 from /home/user/editor/nvi2/cl/cl_funcs.c:28:
/home/user/editor/nvi2/cl/../common/cut.h:33:9: error: unknown type name ‘recno_t’
   33 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:85:
/home/user/editor/nvi2/cl/../common/mark.h:24:9: error: unknown type name ‘recno_t’
   24 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/mark.h:30:9: error: unknown type name ‘recno_t’
   30 |         recno_t  lno;                   /* Line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:87:
/home/user/editor/nvi2/cl/../common/../ex/ex.h:69:9: error: unknown type name ‘recno_t’
   69 |         recno_t start, stop;            /* Start/stop of the range. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:77:9: error: unknown type name ‘recno_t’
   77 |         recno_t   if_lno;               /* Associated line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:94:9: error: unknown type name ‘recno_t’
   94 |         recno_t   range_lno;            /* @/global range: set line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/ex.h:113:9: error: unknown type name ‘recno_t’
  113 |         recno_t   lineno;               /* Command: line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/../ex/ex.h:231:
/home/user/editor/nvi2/cl/../common/../ex/extern.h:44:32: error: unknown type name ‘recno_t’
   44 | int ex_g_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:72:46: error: unknown type name ‘recno_t’
   72 | int ex_readfp(SCR *, char *, FILE *, MARK *, recno_t *, int);
      |                                              ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:78:22: error: unknown type name ‘recno_t’
   78 | int sscr_exec(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:41: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/../ex/extern.h:116:50: error: unknown type name ‘recno_t’
  116 | void ex_cinit(SCR *, EXCMD *, int, int, recno_t, recno_t, int);
      |                                                  ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:88:
/home/user/editor/nvi2/cl/../common/gs.h:26:9: error: unknown type name ‘recno_t’
   26 |         recno_t  lno;                   /* 1-N: file cursor line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/gs.h:90:9: error: unknown type name ‘recno_t’
   90 |         recno_t   if_lno;               /* Current associated line number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:89:
/home/user/editor/nvi2/cl/../common/screen.h:60:9: error: unknown type name ‘recno_t’
   60 |         recno_t  lno;                   /* 1-N: file line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:72:9: error: unknown type name ‘recno_t’
   72 |         recno_t  rptlchange;            /* Ex/vi: last L_CHANGED lno. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:73:9: error: unknown type name ‘recno_t’
   73 |         recno_t  rptlines[L_YANKED + 1];/* Ex/vi: lines changed by last op. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/screen.h:79:9: error: unknown type name ‘recno_t’
   79 |         recno_t  defscroll;             /* Vi: ^D, ^U scroll information. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:90:
/home/user/editor/nvi2/cl/../common/exf.h:22:9: error: unknown type name ‘recno_t’
   22 |         recno_t  c_lno;                 /* Cached line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:23:9: error: unknown type name ‘recno_t’
   23 |         recno_t  c_nlines;              /* Cached lines in the file. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:28:9: error: unknown type name ‘recno_t’
   28 |         recno_t  l_high;                /* Log last + 1 record number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../common/exf.h:29:9: error: unknown type name ‘recno_t’
   29 |         recno_t  l_cur;                 /* Log current record number. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../common/common.h:94:
/home/user/editor/nvi2/cl/../common/extern.h:6:21: error: unknown type name ‘recno_t’
    6 | int cut_line(SCR *, recno_t, size_t, size_t, CB *);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:35:20: error: unknown type name ‘recno_t’
   35 | int db_eget(SCR *, recno_t, CHAR_T **, size_t *, int *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:36:19: error: unknown type name ‘recno_t’
   36 | int db_get(SCR *, recno_t, u_int32_t, CHAR_T **, size_t *);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:37:22: error: unknown type name ‘recno_t’
   37 | int db_delete(SCR *, recno_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:38:27: error: unknown type name ‘recno_t’
   38 | int db_append(SCR *, int, recno_t, CHAR_T *, size_t);
      |                           ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:39:22: error: unknown type name ‘recno_t’
   39 | int db_insert(SCR *, recno_t, CHAR_T *, size_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:40:19: error: unknown type name ‘recno_t’
   40 | int db_set(SCR *, recno_t, CHAR_T *, size_t);
      |                   ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:41:21: error: unknown type name ‘recno_t’
   41 | int db_exist(SCR *, recno_t);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:42:20: error: unknown type name ‘recno_t’
   42 | int db_last(SCR *, recno_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:43:20: error: unknown type name ‘recno_t’
   43 | int db_rget(SCR *, recno_t, char **, size_t *);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:44:20: error: unknown type name ‘recno_t’
   44 | int db_rset(SCR *, recno_t, char *, size_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:45:20: error: unknown type name ‘recno_t’
   45 | void db_err(SCR *, recno_t);
      |                    ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:49:21: error: unknown type name ‘recno_t’
   49 | int log_line(SCR *, recno_t, u_int);
      |                     ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:60:32: error: unknown type name ‘recno_t’
   60 | int mark_insdel(SCR *, lnop_t, recno_t);
      |                                ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:65:25: error: unknown type name ‘recno_t’
   65 | void msgq_status(SCR *, recno_t, u_int);
      |                         ^~~~~~~
/home/user/editor/nvi2/cl/../common/extern.h:121:21: error: unknown type name ‘recno_t’
  121 | int nonblank(SCR *, recno_t, size_t *);
      |                     ^~~~~~~
In file included from /home/user/editor/nvi2/cl/cl_funcs.c:29:
/home/user/editor/nvi2/cl/../vi/vi.h:150:9: error: unknown type name ‘recno_t’
  150 |         recno_t  cs_lno;                /* Line. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../vi/vi.h:198:9: error: unknown type name ‘recno_t’
  198 |         recno_t  lno;   /* 1-N: Physical file line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../vi/vi.h:274:9: error: unknown type name ‘recno_t’
  274 |         recno_t sv_tm_lno;      /* tcmd: saved TMAP lno field. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../vi/vi.h:294:9: error: unknown type name ‘recno_t’
  294 |         recno_t ss_lno; /* 1-N: vi_opt_screens cached line number. */
      |         ^~~~~~~
/home/user/editor/nvi2/cl/../vi/vi.h:299:9: error: unknown type name ‘recno_t’
  299 |         recno_t olno;           /* 1-N: old cursor file line. */
      |         ^~~~~~~
In file included from /home/user/editor/nvi2/cl/../vi/vi.h:384:
/home/user/editor/nvi2/cl/../vi/extern.h:87:40: error: unknown type name ‘recno_t’
   87 |    const CHAR_T *, size_t, ARG_CHAR_T, recno_t, u_long, u_int32_t);
      |                                        ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:88:23: error: unknown type name ‘recno_t’
   88 | int v_txt_auto(SCR *, recno_t, TEXT *, size_t, TEXT *);
      |                       ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:125:26: error: unknown type name ‘recno_t’
  125 | size_t vs_screens(SCR *, recno_t, size_t *);
      |                          ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:126:36: error: unknown type name ‘recno_t’
  126 | size_t vs_columns(SCR *, CHAR_T *, recno_t, size_t *, size_t *);
      |                                    ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:127:22: error: unknown type name ‘recno_t’
  127 | size_t vs_rcm(SCR *, recno_t, int);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:128:25: error: unknown type name ‘recno_t’
  128 | size_t vs_colpos(SCR *, recno_t, size_t);
      |                         ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:129:22: error: unknown type name ‘recno_t’
  129 | int vs_change(SCR *, recno_t, lnop_t);
      |                      ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:130:23: error: unknown type name ‘recno_t’
  130 | int vs_sm_fill(SCR *, recno_t, pos_t);
      |                       ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:131:33: error: unknown type name ‘recno_t’
  131 | int vs_sm_scroll(SCR *, MARK *, recno_t, scroll_t);
      |                                 ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:138:1: error: unknown type name ‘recno_t’
  138 | recno_t vs_sm_nlines(SCR *, SMAP *, recno_t, size_t);
      | ^~~~~~~
/home/user/editor/nvi2/cl/../vi/extern.h:138:37: error: unknown type name ‘recno_t’
  138 | recno_t vs_sm_nlines(SCR *, SMAP *, recno_t, size_t);
      |                                     ^~~~~~~
/home/user/editor/nvi2/cl/cl_funcs.c: In function ‘addstr4’:
/home/user/editor/nvi2/cl/cl_funcs.c:39:19: warning: variable ‘x’ set but not used [-Wunused-but-set-variable]
   39 |         size_t y, x;
      |                   ^
/home/user/editor/nvi2/cl/cl_funcs.c:37:21: warning: variable ‘clp’ set but not used [-Wunused-but-set-variable]
   37 |         CL_PRIVATE *clp;
      |                     ^~~
/home/user/editor/nvi2/cl/cl_funcs.c: In function ‘cl_attr’:
/home/user/editor/nvi2/cl/cl_funcs.c:149:11: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
  149 |         } else
      |           ^~~~
/home/user/editor/nvi2/cl/cl_funcs.c:158:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  158 |                 (void)fflush(stdout);
      |                 ^
/home/user/editor/nvi2/cl/cl_funcs.c: In function ‘cl_deleteln’:
/home/user/editor/nvi2/cl/cl_funcs.c:311:21: warning: variable ‘clp’ set but not used [-Wunused-but-set-variable]
  311 |         CL_PRIVATE *clp;
      |                     ^~~
/home/user/editor/nvi2/cl/cl_funcs.c: In function ‘cl_refresh’:
/home/user/editor/nvi2/cl/cl_funcs.c:520:13: warning: variable ‘gp’ set but not used [-Wunused-but-set-variable]
  520 |         GS *gp;
      |             ^~
/home/user/editor/nvi2/cl/cl_funcs.c: In function ‘cl_suspend’:
/home/user/editor/nvi2/cl/cl_funcs.c:704:13: warning: variable ‘gp’ set but not used [-Wunused-but-set-variable]
  704 |         GS *gp;
      |             ^~
ninja: build stopped: subcommand failed.
```

**Comment by leres** [comment]
Linux does this wierd thing where you don't get full includes/libraries unless you install the "dev" version of the package; I suspect that's what you're running into.

You'll likely need to install libncurses5-dev (or something similar).

**Comment by Chirunos** [comment]
I already have `ncurses-devel` and `ncurses5-devel`, both in version 6.1 and from Update repository with updates from SUSE Linux Enterprise 15

**Comment by lichray** [comment]
> `libdb-4_8-devel` 4.8.30 (Main Repository)

nvi2 uses libdb1

**Comment by Chirunos** [comment]
> nvi2 uses libdb1

Thanks, now I'm getting #140
